[versions]
assemblyai-java = "3.0.0"
bcpkix-jdk18on = "1.77"
betterypermissionhelper = "1.0.3"
filepicker = "9.2.5"
jstyleparser = "4.0.0"
okhttp = "4.12.0"
xposed-legacy = "82"
agp = "8.5.1"
colorpicker = "1.1.0"
dexkit = "2.0.2"
nav = "2.7.7"
kotlin = "2.0.0"


[libraries]
assemblyai-java = { module = "com.assemblyai:assemblyai-java", version.ref = "assemblyai-java" }
bcpkix-jdk18on = { module = "org.bouncycastle:bcpkix-jdk18on", version.ref = "bcpkix-jdk18on" }
betterypermissionhelper = { module = "com.waseemsabir:betterypermissionhelper", version.ref = "betterypermissionhelper" }
colorpicker = { module = "com.jaredrummler:colorpicker", version.ref = "colorpicker" }
dexkit = { module = "org.luckypray:dexkit", version.ref = "dexkit" }
filepicker = { module = "io.github.tutorialsandroid:filepicker", version.ref = "filepicker" }
jstyleparser = { module = "net.sf.cssbox:jstyleparser", version.ref = "jstyleparser" }
libxposed-legacy = { group = "de.robv.android.xposed", name = "api", version.ref = "xposed-legacy" }

androidx-activity = { module = "androidx.activity:activity", version = "1.9.0" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version = "2.1.4" }
androidx-fragment = { module = "androidx.fragment:fragment", version = "1.8.1" }
androidx-navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "nav" }
androidx-navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "nav" }

okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
rikkax-appcompat = { module = "dev.rikka.rikkax.appcompat:appcompat", version = "1.6.1" }
rikkax-core = { module = "dev.rikka.rikkax.core:core", version = "1.4.1" }
rikkax-material = { module = "dev.rikka.rikkax.material:material", version = "2.7.0" }
rikkax-material-preference = { module = "dev.rikka.rikkax.material:material-preference", version = "2.0.0" }
rikkax-widget-borderview = { module = "dev.rikka.rikkax.widget:borderview", version = "1.1.0" }
material = { module = "com.google.android.material:material", version = "1.12.0" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
materialthemebuilder = { id = "dev.rikka.tools.materialthemebuilder", version = "1.4.1" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

